spring.application.name=network_management_system

spring.r2dbc.url=r2dbc:h2:mem:///test
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always
spring.data.r2dbc.repositories.enabled=true
spring.sql.init.platform=h2
spring.r2dbc.generate-unique-name=false
spring.main.web-application-type=reactive

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true